#!/usr/bin/env sh

if [ "$(id -u)" != '0' ]; then
    echo 'Only root can do that' >&2
    exit 1
fi

local_bin_dir='/usr/local/bin'

echo 'Install...'
cd "$(dirname "${0}")" || exit 1
for bin in bin/*; do
    echo "+ ${bin##*/}"
    install -m 755 -o root "${bin}" "${local_bin_dir}/"
done
echo 'Done.'
